apiVersion: v1
kind: Service
metadata:
  name: lab-interpreter
spec:
  type: {{ .Values.service.type }}
  selector:
    app: lab-interpreter
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
