apiVersion: v1
kind: Service
metadata:
  name: phos-sync
spec:
  type: {{ .Values.service.type }}
  selector:
    app: phos-sync
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
