apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-kit
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nutrition-kit
  template:
    metadata:
      labels:
        app: nutrition-kit
    spec:
      containers:
        - name: nutrition-kit
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
