apiVersion: v1
kind: Service
metadata:
  name: nutrition-kit
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nutrition-kit
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
