{{- if (.Values.rbac.create | default false) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "api.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
