apiVersion: v1
kind: Service
metadata:
  name: phos-fhir-bridge
spec:
  type: {{ .Values.service.type }}
  selector:
    app: phos-fhir-bridge
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080

