version: '3.8'

services:
  loadtest:
    build:
      context: .
      dockerfile: Dockerfile.k6
    environment:
      - BASE_URL=http://api-gateway
      - API_VERSION=v1
    volumes:
      - ./results:/results
    command: ["--out", "json=/results/result.json", "script.js"]
    networks:
      - phos-network

networks:
  phos-network:
    external: true
