apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phos-core
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: phos-core.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phos-core
                port:
                  number: {{ .Values.service.port }}
