apiVersion: v1
kind: Service
metadata:
  name: billing-gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app: billing-gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080

